#!/bin/bash

echo "formatting..."
go fmt ./...

echo "sorting imports..."
goimports -l -w .

echo "linting..."
golint ./...

echo "vetting..."
go vet ./...

#echo "static checks..."
#staticcheck ./...

echo "checking missed error checks..."
errcheck ./...

echo "checking memory inefficient structs..."
fieldalignment ./...

echo "performing other code quality checks using golangci-lint..."
golangci-lint run

# TODO: go test script to compare code coverage changes
