version: 2
jobs:
  utils:
    working_directory: ~/
    docker:
      - image: golang:1.23.0-bullseye
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
            - lint-dependencies
            - test-dependencies
      - run:
          name: Install Go Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Install Lint Dependencies
          command: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.0
      - save_cache:
          key: lint-dependencies
          paths:
            - "/go/bin/golangci-lint"
      - run:
          name: Install Test Dependencies
          command: go install gotest.tools/gotestsum@latest
      - save_cache:
          key: test-dependencies
          paths:
            - "/go/bin/gotestsum"
      - run:
          name: Run Lint and Tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
            golangci-lint run --out-format=checkstyle > /tmp/test-reports/lint.xml
            cd /tmp/test-reports
            cat unit-tests.xml
            cat lint.xml
            curl -Os https://uploader.codecov.io/latest/linux/codecov 
            chmod +x codecov 
            ./codecov -t ${{ secrets.CODECOV_BACKEND_TOKEN }}
      - store_test_results:
          path: /tmp/test-reports

workflows:
  version: 2
  build:
    - utils:
        context:
          - utils
        filters:
          branches:
            only:
              - main
