// Code generated by mockery v2.42.1. DO NOT EDIT.

package ports

import mock "github.com/stretchr/testify/mock"

// Closer is an autogenerated mock type for the Closer type
type Closer struct {
	mock.Mock
}

type Closer_Expecter struct {
	mock *mock.Mock
}

func (_m *Closer) EXPECT() *Closer_Expecter {
	return &Closer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *Closer) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Closer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Closer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Closer_Expecter) Close() *Closer_Close_Call {
	return &Closer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Closer_Close_Call) Run(run func()) *Closer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Closer_Close_Call) Return(_a0 error) *Closer_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Closer_Close_Call) RunAndReturn(run func() error) *Closer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// NewCloser creates a new instance of Closer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCloser(t interface {
	mock.TestingT
	Cleanup(func())
}) *Closer {
	mock := &Closer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
