// Code generated by mockery v2.42.1. DO NOT EDIT.

package ports

import (
	context "context"

	models "go.ssnk.in/utils/database/models"
	mock "github.com/stretchr/testify/mock"
)

// MockDatabase is an autogenerated mock type for the Database type
type MockDatabase struct {
	mock.Mock
}

type MockDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabase) EXPECT() *MockDatabase_Expecter {
	return &MockDatabase_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: _a0, _a1
func (_m *MockDatabase) Begin(_a0 context.Context, _a1 ...interface{}) (*models.Response, error) {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 *models.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) (*models.Response, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) *models.Response); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...interface{}) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockDatabase_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...interface{}
func (_e *MockDatabase_Expecter) Begin(_a0 interface{}, _a1 ...interface{}) *MockDatabase_Begin_Call {
	return &MockDatabase_Begin_Call{Call: _e.mock.On("Begin",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockDatabase_Begin_Call) Run(run func(_a0 context.Context, _a1 ...interface{})) *MockDatabase_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockDatabase_Begin_Call) Return(_a0 *models.Response, _a1 error) *MockDatabase_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_Begin_Call) RunAndReturn(run func(context.Context, ...interface{}) (*models.Response, error)) *MockDatabase_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields:
func (_m *MockDatabase) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDatabase_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDatabase_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDatabase_Expecter) Close() *MockDatabase_Close_Call {
	return &MockDatabase_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDatabase_Close_Call) Run(run func()) *MockDatabase_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabase_Close_Call) Return(_a0 error) *MockDatabase_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDatabase_Close_Call) RunAndReturn(run func() error) *MockDatabase_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Configure provides a mock function with given fields: _a0, _a1
func (_m *MockDatabase) Configure(_a0 context.Context, _a1 ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) error); ok {
		r0 = rf(_a0, _a1...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDatabase_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type MockDatabase_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...interface{}
func (_e *MockDatabase_Expecter) Configure(_a0 interface{}, _a1 ...interface{}) *MockDatabase_Configure_Call {
	return &MockDatabase_Configure_Call{Call: _e.mock.On("Configure",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockDatabase_Configure_Call) Run(run func(_a0 context.Context, _a1 ...interface{})) *MockDatabase_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockDatabase_Configure_Call) Return(_a0 error) *MockDatabase_Configure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDatabase_Configure_Call) RunAndReturn(run func(context.Context, ...interface{}) error) *MockDatabase_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *MockDatabase) Create(_a0 context.Context, _a1 ...interface{}) (*models.Response, error) {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) (*models.Response, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) *models.Response); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...interface{}) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDatabase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...interface{}
func (_e *MockDatabase_Expecter) Create(_a0 interface{}, _a1 ...interface{}) *MockDatabase_Create_Call {
	return &MockDatabase_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockDatabase_Create_Call) Run(run func(_a0 context.Context, _a1 ...interface{})) *MockDatabase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockDatabase_Create_Call) Return(_a0 *models.Response, _a1 error) *MockDatabase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_Create_Call) RunAndReturn(run func(context.Context, ...interface{}) (*models.Response, error)) *MockDatabase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *MockDatabase) Delete(_a0 context.Context, _a1 ...interface{}) (*models.Response, error) {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *models.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) (*models.Response, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) *models.Response); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...interface{}) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDatabase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...interface{}
func (_e *MockDatabase_Expecter) Delete(_a0 interface{}, _a1 ...interface{}) *MockDatabase_Delete_Call {
	return &MockDatabase_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockDatabase_Delete_Call) Run(run func(_a0 context.Context, _a1 ...interface{})) *MockDatabase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockDatabase_Delete_Call) Return(_a0 *models.Response, _a1 error) *MockDatabase_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_Delete_Call) RunAndReturn(run func(context.Context, ...interface{}) (*models.Response, error)) *MockDatabase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *MockDatabase) Execute(_a0 context.Context, _a1 ...interface{}) (*models.Response, error) {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *models.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) (*models.Response, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) *models.Response); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...interface{}) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockDatabase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...interface{}
func (_e *MockDatabase_Expecter) Execute(_a0 interface{}, _a1 ...interface{}) *MockDatabase_Execute_Call {
	return &MockDatabase_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockDatabase_Execute_Call) Run(run func(_a0 context.Context, _a1 ...interface{})) *MockDatabase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockDatabase_Execute_Call) Return(_a0 *models.Response, _a1 error) *MockDatabase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_Execute_Call) RunAndReturn(run func(context.Context, ...interface{}) (*models.Response, error)) *MockDatabase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: _a0, _a1
func (_m *MockDatabase) Query(_a0 context.Context, _a1 ...interface{}) (*models.Response, error) {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *models.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) (*models.Response, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) *models.Response); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...interface{}) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockDatabase_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...interface{}
func (_e *MockDatabase_Expecter) Query(_a0 interface{}, _a1 ...interface{}) *MockDatabase_Query_Call {
	return &MockDatabase_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockDatabase_Query_Call) Run(run func(_a0 context.Context, _a1 ...interface{})) *MockDatabase_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockDatabase_Query_Call) Return(_a0 *models.Response, _a1 error) *MockDatabase_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_Query_Call) RunAndReturn(run func(context.Context, ...interface{}) (*models.Response, error)) *MockDatabase_Query_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: _a0, _a1
func (_m *MockDatabase) Rollback(_a0 context.Context, _a1 ...interface{}) (*models.Response, error) {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 *models.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) (*models.Response, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) *models.Response); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...interface{}) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockDatabase_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...interface{}
func (_e *MockDatabase_Expecter) Rollback(_a0 interface{}, _a1 ...interface{}) *MockDatabase_Rollback_Call {
	return &MockDatabase_Rollback_Call{Call: _e.mock.On("Rollback",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockDatabase_Rollback_Call) Run(run func(_a0 context.Context, _a1 ...interface{})) *MockDatabase_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockDatabase_Rollback_Call) Return(_a0 *models.Response, _a1 error) *MockDatabase_Rollback_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_Rollback_Call) RunAndReturn(run func(context.Context, ...interface{}) (*models.Response, error)) *MockDatabase_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *MockDatabase) Update(_a0 context.Context, _a1 ...interface{}) (*models.Response, error) {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) (*models.Response, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) *models.Response); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...interface{}) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDatabase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...interface{}
func (_e *MockDatabase_Expecter) Update(_a0 interface{}, _a1 ...interface{}) *MockDatabase_Update_Call {
	return &MockDatabase_Update_Call{Call: _e.mock.On("Update",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockDatabase_Update_Call) Run(run func(_a0 context.Context, _a1 ...interface{})) *MockDatabase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockDatabase_Update_Call) Return(_a0 *models.Response, _a1 error) *MockDatabase_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_Update_Call) RunAndReturn(run func(context.Context, ...interface{}) (*models.Response, error)) *MockDatabase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDatabase creates a new instance of MockDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabase {
	mock := &MockDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
